Explain better the project generator. Related #43
MarsBased/handbook pull request #47
Opened 2021-04-06 11:43 UTC by danigb

Commented here https://github.com/MarsBased/handbook/issues/43#issuecomment-808246198

2021-04-06 11:44 UTC, davidgg approved these changes
100% yes!

2021-04-06 14:17 UTC, xredo requested changes
Great! I find it less confusing now! 👍

I think that there is a grammar typo. I have left the suggestion.

2021-04-06 14:17 UTC, xredo commented on guides/development/react-guidelines.md
> +We will consider using another system (mostly [next.js](https://nextjs.org/)) for newer projects, specially if has important SEO requirements.
```suggestion
We will consider using another system (mostly [next.js](https://nextjs.org/)) for newer projects, specially if they have important SEO requirements.
```

2021-04-08 12:12 UTC, oriolbcn approved these changes
nice 👏

2021-04-12 11:27 UTC, merged